const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const path = require('path');
const swaggerUi = require('swagger-ui-express');
const swaggerSpec = require('./config/swagger');

// Multi-layer specific imports
const config = require('./config/multilayer.config');
const { initializeMultilayerDatabases } = require('./config/multilayer.database');
const mqttService = require('./services/multilayer.mqttService');
const layerAutomationService = require('./services/layerAutomation');
const batchScheduler = require('./services/batchScheduler');
const { errorHandler } = require('./middleware/errorHandler');

// Routes
const tvRoutes = require('./routes/tvRoutes');
const imageRoutes = require('./routes/imageRoutes');
const dashboardRoutes = require('./routes/dashboardRoutes');
const layerRoutes = require('./routes/layerRoutes');
const courtHearingRoutes = require('./routes/courtHearingRoutes');
const presetRoutes = require('./routes/presetRoutes');
const bulkRoutes = require('./routes/bulkRoutes');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

// Security middleware
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com"],
      scriptSrc: ["'self'", "'unsafe-inline'"],
      imgSrc: ["'self'", "data:", "blob:"],
      connectSrc: ["'self'", "ws:", "wss:"],
      fontSrc: ["'self'", "https://cdnjs.cloudflare.com"],
      upgradeInsecureRequests: null,
    },
  },
}));

// CORS configuration
const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests with no origin (mobile apps, Postman, etc.)
    if (!origin) return callback(null, true);
    
    // Check against allowed origins
    if (config.security.allowedOrigins.length === 0 || 
        config.security.allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error('Not allowed by CORS'));
    }
  },
  credentials: true,
  optionsSuccessStatus: 200
};
app.use(cors(corsOptions));

// Body parsing middleware
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// Logging middleware
if (config.isDevelopment()) {
  app.use(morgan('dev'));
} else {
  app.use(morgan('combined'));
}

// Static files
app.use(express.static(path.join(__dirname, '../public')));
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));

// API Documentation
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
  customCss: '.swagger-ui .topbar { display: none }',
  customSiteTitle: 'Digital Signage API Docs'
}));

// Serve OpenAPI spec as JSON
app.get('/api-docs.json', (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(swaggerSpec);
});

/**
 * @openapi
 * /health:
 *   get:
 *     summary: Health check endpoint
 *     description: Returns the health status of the server and its components
 *     tags:
 *       - Health
 *     responses:
 *       200:
 *         description: Server is healthy
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/HealthResponse'
 */
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    mode: 'multi-layer',
    timestamp: new Date().toISOString(),
    databases: config.database.databases,
    mqtt_prefix: config.mqtt.topics.prefix,
    api_docs: '/api-docs'
  });
});

/**
 * @openapi
 * /api/version:
 *   get:
 *     summary: Get version information
 *     description: Returns git version, commit hash, branch, and build information
 *     tags:
 *       - Health
 *     responses:
 *       200:
 *         description: Version information
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/VersionResponse'
 */
app.get('/api/version', (req, res) => {
  const fs = require('fs');
  const { execSync } = require('child_process');
  
  try {
    // Read static version info from version.json (generated by git hook)
    let versionInfo;
    try {
      const versionJson = fs.readFileSync(path.join(__dirname, 'version.json'), 'utf8');
      versionInfo = JSON.parse(versionJson);
    } catch (error) {
      console.warn('Could not read version.json, falling back to git commands');
      // Fallback to live git commands if version.json doesn't exist
      const commitHash = execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim();
      const commitShort = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
      const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
      const version = execSync('git describe --tags --always', { encoding: 'utf8' }).trim();
      
      versionInfo = {
        version: version,
        commit_hash: commitHash,
        commit_short: commitShort,
        branch: branch,
        build_time: new Date().toISOString()
      };
    }
    
    // Check for dirty working directory in development
    let isDirty = false;
    if (process.env.NODE_ENV !== 'production') {
      try {
        const gitStatus = execSync('git status --porcelain', { encoding: 'utf8' }).trim();
        isDirty = gitStatus.length > 0;
      } catch (error) {
        // Ignore git errors in development
      }
    }
    
    // Read Management UI version from package.json
    let managementVersion = 'unknown';
    try {
      const packagePath = path.join(__dirname, '../package.json');
      const packageJson = fs.readFileSync(packagePath, 'utf8');
      const packageInfo = JSON.parse(packageJson);
      managementVersion = packageInfo.version;
    } catch (error) {
      console.warn('Could not read package.json version:', error.message);
    }
    
    // Append -dirty suffix if there are uncommitted changes
    const displayVersion = isDirty ? `${versionInfo.version}-dirty` : versionInfo.version;
    
    res.json({
      commit_hash: versionInfo.commit_hash,
      commit_short: versionInfo.commit_short,
      branch: versionInfo.branch,
      build_time: versionInfo.build_time,
      version: displayVersion,
      management_ui_version: managementVersion,
      is_dirty: isDirty,
      mode: 'multi-layer'
    });
  } catch (error) {
    console.error('Error getting version info:', error);
    res.json({
      commit_hash: 'unknown',
      commit_short: 'unknown',
      branch: 'unknown',
      build_time: new Date().toISOString(),
      version: 'unknown',
      management_ui_version: 'unknown',
      is_dirty: false,
      mode: 'multi-layer'
    });
  }
});

// API routes
app.use('/api/tvs', tvRoutes);
app.use('/api/images', imageRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/layers', layerRoutes); // New layer management routes
const alertTemplateRoutes = require('./routes/alertTemplateRoutes');
const alertRoutes = require('./routes/alertRoutes');
app.use('/api/alerts/templates', alertTemplateRoutes); // Alert template management (must be before /api/alerts)
app.use('/api/alerts', alertRoutes); // Emergency alert routes
app.use('/api/hearings', courtHearingRoutes); // Court hearing management routes
app.use('/api/presets', presetRoutes); // Zone preset templates
app.use('/api/bulk', bulkRoutes); // Bulk operations for multi-TV management

// WebSocket handling for real-time updates
wss.on('connection', (ws) => {
  console.log('New WebSocket connection (multi-layer mode)');
  
  ws.on('message', (message) => {
    try {
      const data = JSON.parse(message);
      console.log('WebSocket message:', data);
      
      // Handle layer-specific WebSocket messages
      if (data.type === 'subscribe_layers') {
        ws.subscribedTvId = data.tv_id;
        ws.send(JSON.stringify({ 
          type: 'subscription_confirmed', 
          tv_id: data.tv_id 
        }));
      }
    } catch (error) {
      console.error('WebSocket message error:', error);
    }
  });
  
  ws.on('close', () => {
    console.log('WebSocket connection closed');
  });
});

// MQTT event forwarding to WebSocket clients
mqttService.on('message', ({ topic, payload }) => {
  // Forward layer updates to subscribed WebSocket clients
  wss.clients.forEach((client) => {
    if (client.readyState === WebSocket.OPEN) {
      // Extract TV ID from topic
      const topicParts = topic.split('/');
      const tvIdIndex = topicParts.indexOf('tv') + 1;
      const tvId = topicParts[tvIdIndex];
      
      // Only send to clients subscribed to this TV
      if (!client.subscribedTvId || client.subscribedTvId === tvId) {
        client.send(JSON.stringify({
          type: 'mqtt_message',
          topic,
          payload,
          timestamp: new Date().toISOString()
        }));
      }
    }
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Endpoint not found' });
});

// Error handling middleware (must be last)
app.use(errorHandler);

// Graceful shutdown handling
let isShuttingDown = false;

async function gracefulShutdown(signal) {
  if (isShuttingDown) return;
  isShuttingDown = true;
  
  console.log(`\n${signal} received. Starting graceful shutdown...`);
  
  // Stop accepting new connections
  server.close(() => {
    console.log('HTTP server closed');
  });
  
  // Close WebSocket connections
  wss.clients.forEach((client) => {
    client.close();
  });
  
  // Stop layer automation
  layerAutomationService.stop();
  console.log('Layer automation stopped');

  // Stop batch scheduler
  batchScheduler.stop();
  console.log('Batch scheduler stopped');

  // Disconnect from MQTT
  await mqttService.disconnect();
  console.log('MQTT disconnected');
  
  // Wait for pending operations
  setTimeout(() => {
    console.log('Graceful shutdown complete');
    process.exit(0);
  }, config.server.shutdownTimeout);
}

// Register shutdown handlers
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

// Initialize and start server
async function startServer() {
  try {
    // Initialize multi-layer databases
    console.log('Initializing multi-layer databases...');
    await initializeMultilayerDatabases();
    console.log('Multi-layer databases initialized');
    
    // Connect to MQTT broker
    console.log('Connecting to MQTT broker (multi-layer mode)...');
    await mqttService.connect();
    
    // Start layer automation service
    console.log('Starting layer automation service...');
    layerAutomationService.start();

    // Initialize alert template service
    console.log('Initializing alert template service...');
    const templateService = require('./services/templateService');
    await templateService.initialize();

    // Start alert queue service
    console.log('Starting alert queue service...');
    const queueService = require('./services/alertQueueService');
    queueService.start();

    // Start alert schedule service
    console.log('Starting alert schedule service...');
    const scheduleService = require('./services/alertScheduleService');
    scheduleService.start();

    // Start batch scheduler
    console.log('Starting batch scheduler...');
    batchScheduler.start();

    // Start HTTP server
    const port = config.server.port;
    const host = config.server.host;
    
    server.listen(port, host, () => {
      console.log(`
========================================
Multi-layer Digital Signage Server
========================================
Mode: ${config.server.environment}
Server: http://${host}:${port}
API Docs: http://${host}:${port}/api-docs
Databases: ${Object.values(config.database.databases).join(', ')}
MQTT Prefix: ${config.mqtt.topics.prefix}
WebSocket: ws://${host}:${port}
========================================
      `);
    });
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
}

// Handle unhandled promise rejections
process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection at:', promise, 'reason:', reason);
  // Don't exit in development
  if (!config.isDevelopment()) {
    gracefulShutdown('UNHANDLED_REJECTION');
  }
});

// Start the server
startServer();

module.exports = { app, server, wss };